### ISSUE TITLE
IP address

### ISSUE THREAD

**Issue by vatsal1511** [asim/kv#1]
Hey,
Firstly thanks for the repo. I am a beginner. While I was going through this, I was unable to figure out the piece of code where the IP of the remote host is being taken and displayed on the screen.
Is there a way I can get the IP addresses of all the hosts for further use?

Thanks

**Comment by asim** [comment]
Hi,

This is just a simple example. It prints the address of the local node here https://github.com/asim/memberlist/blob/master/memberlist.go#L202. You take this address and hand it to any other instance of a program being run so that it has a seed node. The readme demonstrates this.

This example just builds on hashicorp's memberlist https://godoc.org/github.com/hashicorp/memberlist. We retrieve the local node on line 201 https://github.com/asim/memberlist/blob/master/memberlist.go#L201. Memberlist gives you a number of methods to call including Members which gives you the full list https://godoc.org/github.com/hashicorp/memberlist#Memberlist.Members. Please read the godoc.

Thanks
